name: Build

on:
  workflow_call:

jobs:
  make_binaries:
    name: Make Binaries
    runs-on: ${{ matrix.target.host || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.21.x"]
        target:
          - os: linux
    steps:
      - name: Install required packages
        run: sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev xorg-dev

      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          # cache:
          # - description: Used to specify whether caching is needed. Set to true, if you'd like to enable caching.
          # default: false
          go-version-file: "go.mod"
          cache-dependency-path: |
            go.sum

      - name: Install Fyne-cross
        # working-directory: fyne-cross
        run: go install github.com/fyne-io/fyne-cross@latest

      # attempt to use "go install" but fallback to "go get"
      - name: Install Fyne
        run: |
          go install fyne.io/fyne/v2/cmd/fyne@latest ||
          go get fyne.io/fyne/v2/cmd/fyne@latest

      - name: Install Podman
        if: ${{ runner.os == 'macos' }}
        run: |
          brew install podman
          podman machine init
          podman machine start

      - name: "Build MastoTool (${{ matrix.target.os }}, ${{ matrix.go-version }})"
        run: |
          fyne-cross \
            ${{ matrix.target.os }} \
            ${{ matrix.target.args }} \
            -name mastotool${{ matrix.target.ext }} \
            -app-id com.github.PaulWaldo.mastotool
      # - name: "Build MastoTool (${{ matrix.target.os }}, ${{ matrix.go-version }})"
      # runs-on: ${{ matrix.target.host || 'ubuntu-latest' }}
      # strategy:
      #   fail-fast: false
      # matrix:
      #   # use max/min supported Go versions
      #   # go-version: ["1.18.x", "1.21.x"]
      #   go-version: ["1.21.x"]
      #   target:
      #     - os: linux
      # - os: windows
      #   ext: .exe
      # - os: freebsd
      # - os: android
      #   args: -app-id calc.sha${{ github.sha }}
      ## Not shared darwin image is available at the moment
      # - os: darwin
      #  args: -app-id calc.sha${{ github.sha }}
      #  host: macos-latest
      # - os: web

      ## Currently not easily supported from GitHub actions.
      ## https://github.com/fyne-io/fyne-cross/pull/104#issuecomment-1099494308
      # - os: ios
      #   args: -app-id calc.sha${{ github.sha }}
      #   host: macos-latest

  #   - name: Cache build artifacts
  #     uses: actions/cache@v3
  #     with:
  #       path: |
  #         ~/go/pkg/mod
  #         ~/.cache/go-build
  #         ~/.cache/fyne-cross
  #       key: ${{ runner.os }}-build-cache-${{ hashFiles('**/go.sum') }}

  #   - name: Install Fyne-cross
  #     # working-directory: fyne-cross
  #     run: go install github.com/fyne-io/fyne-cross@latest

  #     # attempt to use "go install" but fallback to "go get"
  #   #   - name: Install Fyne
  #   #     run: |
  #   #       go install fyne.io/fyne/v2/cmd/fyne@latest ||
  #   #       go get fyne.io/fyne/v2/cmd/fyne@latest

  #   #   - name: Install Podman
  #   #     if: ${{ runner.os == 'macos' }}
  #   #     run: |
  #   #       brew install podman
  #   #       podman machine init
  #   #       podman machine start

  #   - name: Build
  #     # working-directory: calculator
  #     run: |
  #       fyne-cross \
  #         ${{ matrix.target.os }} \
  #         ${{ matrix.target.args }} \
  #         -name mastotool${{ matrix.target.ext }} \
  #         -app-id com.github.PaulWaldo.mastotool
