# name: "Setup code"

on:
  workflow_call:

jobs:
  setup:
    name: "Prepare"
    runs-on: "ubuntu-latest"
    steps:
      - name: Install required packages
        run: sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev xorg-dev

      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          # cache:
            # - description: Used to specify whether caching is needed. Set to true, if you'd like to enable caching.
            # default: false
          go-version-file: "go.mod"
          cache-dependency-path: |
             go.sum
        # with:
        #   go-version: "1.20"
